# Loops, range, and list comprehension

## Paragraph 01

In [1]:
for i in range(10):
    print (i)

0
1
2
3
4
5
6
7
8
9


In [2]:
x = [1,2,3]
for i in x:
    print (i*i)

1
4
9


In [3]:
x = [1,2,3]
y = [2,3,4]
n = len(x)
s = 0
for i in range(n):
    s +=x[i]*y[i]
print (s)

20


In [4]:
s = 0
for i,j in zip(x,y):
    s+=i*j
print (s)

20


In [5]:
print (sum([i*j for i,j in zip(x,y)]))

20


In [6]:
import numpy as np
print (np.dot(x,y))

20


## 02 - List Comprehension

S is the set of all y = f(x), such that x is taken from the set Q

In [7]:
def f(x):
    return 2*x
S = [f(x) for x in range(10)]
print (S)

# or better as
Q = range(10)
S = [f(x) for x in Q]
print (S)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [8]:
import numpy as np
n = 3
m = 2

def g(x,y):
    return x + 2*y

def ff(xx):
    x = xx[:,0]
    y = xx[:,1]
    return x + 2*y

Q = range(n)
K = range(m)
print ([[0 for i in Q] for j in K])
print ([[g(i,j) for i in Q] for j in K])

[[0, 0, 0], [0, 0, 0]]
[[0, 1, 2], [2, 3, 4]]


In [9]:
Q = np.array(Q)
K = np.array(K)
print (len(K))
print (len(Q))

vv = np.array([[i,j] for i in Q for j in K])
print (vv)

print (vv[:,1])
print (vv[:,0])

2
3
[[0 0]
 [0 1]
 [1 0]
 [1 1]
 [2 0]
 [2 1]]
[0 1 0 1 0 1]
[0 0 1 1 2 2]


In [10]:
print (g(vv[:,0], vv[:,1]))
print (ff(vv))

[0 2 1 3 2 4]
[0 2 1 3 2 4]


In [11]:
print (sum(g(vv[:,0], vv[:,1])))
print (sum(ff(vv)))

12
12


## 03 - List comprehension with lambda and %timeit

In [12]:
import numpy as np
mydata = 100*np.random.randn(10000) + 500

av = np.mean(mydata)
st = np.std(mydata)
print (av)
print (st)

stvar = [(ii - av)/st for ii in mydata]
print (np.mean(stvar))
print (np.std(stvar))

500.20788428755253
100.7330600210871
-1.0658141036401503e-17
1.0000000000000002


In [13]:
stvar3 = [lambda x: (x - av)/st for x in mydata]
# You cannot run a mean and st on stvar3, 
#print (np.mean(stvar3))
#print (np.std(stvar3))

# so either you try this way, by using a map.
# NOTE - THIS IS FOR python 3. In python yu did NOT need to use list(map()) below
stvar2 = list(map(lambda x: (x - av)/st, mydata))
print (np.mean(stvar2))
print (np.std(stvar2))

# or this way, lambda first and then use the function ff()
ff = lambda x: (x - av)/st
stvar3 = ff(mydata)
print (np.mean(stvar3))
print (np.std(stvar3))

-1.0658141036401503e-17
1.0000000000000002
-1.0658141036401503e-17
1.0000000000000002


In [14]:
# and now check out the fastest way of running mean and st.dev on a vector of N(0,1)
# The winner is ff4!!!
xx = 100*np.random.randn(100000) + 500

def ff1(x):    
    av = np.mean(x)
    st = np.std(x)
    stvar = [(ii - av)/st for ii in x]
    return [np.mean(stvar), np.std(stvar)]

def ff2(x):    
    av = np.mean(x)
    st = np.std(x)
    stvar = list(map(lambda x: (x - av)/st, x))
    return [np.mean(stvar), np.std(stvar)]

def ff3(x):    
    av = np.mean(x)
    st = np.std(x)
    ff = lambda x: (x - av)/st
    stvar = ff(xx)
    return [np.mean(stvar), np.std(stvar)]

def ff4(x):    
    av = np.mean(x)
    st = np.std(x)
    def ff(x):
        return (x - av)/st
    stvar = ff(x)
    return [np.mean(stvar), np.std(stvar)]


%timeit ff1(xx)
%timeit ff2(xx)
%timeit ff3(xx)
%timeit ff4(xx)

43.1 ms ± 901 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
52.3 ms ± 3.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.18 ms ± 65.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
1.85 ms ± 271 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
