# Linear Systems (invertible) with numpy.linalg.solve 

In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,2],[2,8,5]])
b = np.array([5, 10, 15])

x = np.linalg.solve(A,b) # THIS IS THE FASTEST WAY
print x
print A.dot(x)

[0.46511628 1.39534884 0.58139535]
[ 5. 10. 15.]


In [2]:
Ainv = np.linalg.inv(A)

xx = Ainv.dot(b)          # THIS IS NOT SO FAST AS ABOVE
print xx
print A.dot(xx)

[0.46511628 1.39534884 0.58139535]
[ 5. 10. 15.]


In [4]:
# Test which is FAST
def solvere(A, b):
    return np.linalg.solve(A,b)
def solvereInv(A, b):
    Ainv = np.linalg.inv(A)
    return Ainv.dot(b)

%timeit solvere(A, b)    # This is the Fastest!
%timeit solvereInv(A, b) # This is NOT the Fastest!

The slowest run took 11.92 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 9.98 µs per loop
The slowest run took 8.54 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 30.2 µs per loop


In [5]:
AA = np.random.rand(3000,3000)
bb = np.random.rand(3000)
%timeit solvere(AA, bb)
%timeit solvereInv(AA, bb)

1 loop, best of 3: 389 ms per loop
1 loop, best of 3: 1.25 s per loop
