# Solving two dim non-linear system with root from scipy.optimize

In [3]:
import numpy as np
from scipy.optimize import root

In [4]:
import matplotlib.pyplot as plt

### Root finding for solving two dimensional non-linear system, with Levenberg-Marquardt solver¶

In [6]:
# ********************************************
# Consider now a set of non-linear equations
# ********************************************

# x*cos(y) = 4
# x*y - y  = 5

# We define the objective function so that 
# the Jacobian is retunrned.
# To do so we set the jac parameter to TRUE.
# The Levenberg-Marquardt solver is set with method='lm' 
def func2(x):
    f  = [x[0] * np.cos(x[1]) - 4, x[1]*x[0] - x[1] - 5]
    df = np.array(
        [[np.cos(x[1]), -x[0] * np.sin(x[1])],
        [x[1], x[0] - 1]]
                 )
    return f, df

sol = root(func2, [1, 1], jac=True, method='lm')
print (sol)

   cov_x: array([[ 0.87470958, -0.02852752],
       [-0.02852752,  0.01859874]])
    fjac: array([[ 7.52318843, -0.73161761],
       [ 0.24535902, -1.06922242]])
     fun: array([0., 0.])
    ipvt: array([2, 1], dtype=int32)
 message: 'The relative error between two consecutive iterates is at most 0.000000'
    nfev: 8
    njev: 7
     qtf: array([9.53474074e-13, 1.20388645e-13])
  status: 2
 success: True
       x: array([6.50409711, 0.90841421])


In [7]:
print (sol.x)

[6.50409711 0.90841421]


In [9]:
# Now we print both function and the Jacobian
print (func2(sol.x)) 

([0.0, 0.0], array([[ 0.61499697, -5.12867226],
       [ 0.90841421,  5.50409711]]))


In [10]:
 # the function
def funz(x):
    f = [x[0] * np.cos(x[1]) - 4, x[1]*x[0] - x[1] - 5]
    return f
# the gradient
def Gradfunz(x):
    df = np.array([[np.cos(x[1]), -x[0] * np.sin(x[1])],[x[1], x[0] - 1]])
    return df
# it returns both the function and the gradient
def func3(x):
    return funz(x), Gradfunz(x)

sol3 = root(func3, [1, 1], jac=True, method='lm')
print (sol3) # the output

   cov_x: array([[ 0.87470958, -0.02852752],
       [-0.02852752,  0.01859874]])
    fjac: array([[ 7.52318843, -0.73161761],
       [ 0.24535902, -1.06922242]])
     fun: array([0., 0.])
    ipvt: array([2, 1], dtype=int32)
 message: 'The relative error between two consecutive iterates is at most 0.000000'
    nfev: 8
    njev: 7
     qtf: array([9.53474074e-13, 1.20388645e-13])
  status: 2
 success: True
       x: array([6.50409711, 0.90841421])


In [11]:
print (sol3.x)
print (funz(sol3.x))
print (Gradfunz(sol3.x))
print (" -------------------------------------------- ")
print (sol3.fjac)

[6.50409711 0.90841421]
[0.0, 0.0]
[[ 0.61499697 -5.12867226]
 [ 0.90841421  5.50409711]]
 -------------------------------------------- 
[[ 7.52318843 -0.73161761]
 [ 0.24535902 -1.06922242]]


In [13]:
def funz(x):
    f = [x[0] * np.cos(x[1]) - 4, x[1]*x[0] - x[1] - 5]
    return f


sol3 = root(funz, [1, 1])
print (sol3)

  status: 1
 success: True
     qtf: array([  6.25677398e-08,   2.40104775e-08])
    nfev: 17
       r: array([-1.0907073 , -1.7621827 , -7.37420598])
     fun: array([  3.73212572e-12,   1.61701763e-11])
       x: array([ 6.50409711,  0.90841421])
 message: 'The solution converged.'
    fjac: array([[-0.56248005, -0.82681085],
       [ 0.82681085, -0.56248005]])


In [12]:
print (sol3.x)
print (funz(sol3.x))
print (Gradfunz(sol3.x))

[6.50409711 0.90841421]
[0.0, 0.0]
[[ 0.61499697 -5.12867226]
 [ 0.90841421  5.50409711]]
