# Eigenvalues and Eigenvectors

In [2]:
import sympy
import numpy as np
from scipy import linalg as la

In [4]:
A = np.array([[3.0, -4.0], [-4.0, 2.0]])
print (A)
print (" ---------------------------- ")
evals, evecs = la.eig(A)
print (evals )
print (evecs)
print (np.real(evals).argsort())
n  = len(evals)
print (np.real(evals).argsort()[::-1][:n])
idx = np.real(evals).argsort()
idx2= np.real(evals).argsort()[::-1][:n]
for i in idx2:
    print  (np.real(evals[i]))
    
for i in idx:
    print  (np.real(evals[i]))

[[ 3. -4.]
 [-4.  2.]]
 ---------------------------- 
[ 6.53112887+0.j -1.53112887+0.j]
[[ 0.74967818  0.66180256]
 [-0.66180256  0.74967818]]
[1 0]
[0 1]
6.531128874149275
-1.531128874149275
-1.531128874149275
6.531128874149275


In [7]:
A = np.array([[1.0, 3], [2, 2.0]])
print (A)
print (" ----------------------------- ")
evals, evecs = la.eig(A)
print (evals )
print (evecs)
print (" ----------------------------- ")

n  = len(evals)
idx = np.real(evals).argsort()
idx2= np.real(evals).argsort()[::-1][:n]
for i in idx2:
    print  (np.real(evals[i]))
print (" ----------------------------- ")
    
for i in idx:
    print  (np.real(evals[i]))

[[1. 3.]
 [2. 2.]]
 ----------------------------- 
[-1.+0.j  4.+0.j]
[[-0.83205029 -0.70710678]
 [ 0.5547002  -0.70710678]]
 ----------------------------- 
4.0
-1.0
 ----------------------------- 
-1.0
4.0
