# Eigenvalues and Eigenvectors

Linear Algebra - Linear Equation Systems 

a) Symbolic and numeric

b) Rectangular systems 

c) Underdetermined (fat matrices)

d) Overdetermined  (long skinny matrices for least squares)

Eigenvalue problems

Optimization - NonLinear Equations

a) Univariate (Bisection, Newton, Optimization Methods)

b) Multivariate (Jacobian and Hessian matrices)

In [2]:
from scipy import linalg as la
from scipy import optimize as op
import sympy
sympy.init_printing()
import numpy as np

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline

import matplotlib as mpl
mpl.rcParams["font.family"] = "serif"
mpl.rcParams["font.size"] = "12"

In [4]:
from __future__ import division

## Eigenvalue examples

In [5]:
A = np.array([[0.8, 0.3], [0.2, 0.7]])
A

array([[0.8, 0.3],
       [0.2, 0.7]])

In [6]:
evals, evecs = la.eig(A)
print (evals) 
print (evecs)

[1. +0.j 0.5+0.j]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [7]:
# A*eigenvector[1] = eigenvalue(1) * eigenvector[1]
# A*eigenvector[2] = eigenvalue(2) * eigenvector[2]
print (A.dot(evecs[:,0]))
print (evals[0]*evecs[:,0])

print (A.dot(evecs[:,1]))
print (evals[1]*evecs[:,1])

[0.83205029 0.5547002 ]
[0.83205029+0.j 0.5547002 +0.j]
[-0.35355339  0.35355339]
[-0.35355339+0.j  0.35355339+0.j]


In [8]:
A = np.array([[1, 3, 5], [3, 5, 3], [5, 3, 9]])

In [9]:
evals, evecs = la.eig(A)

In [10]:
evals

array([13.35310908+0.j, -1.75902942+0.j,  3.40592034+0.j])

In [11]:
evecs

array([[ 0.42663918,  0.90353276, -0.04009445],
       [ 0.43751227, -0.24498225, -0.8651975 ],
       [ 0.79155671, -0.35158534,  0.49982569]])

In [12]:
print (A.dot(evecs[:,0]))
print (evals[0]*evecs[:,0])

print (A.dot(evecs[:,1]))
print (evals[1]*evecs[:,1])

[ 5.69695953  5.842149   10.5697431 ]
[ 5.69695953+0.j  5.842149  +0.j 10.5697431 +0.j]
[-1.5893407   0.43093099  0.61844896]
[-1.5893407 +0.j  0.43093099-0.j  0.61844896-0.j]


In [13]:
print (la.eigvalsh(A))
print (evals)
print (" ------------- ")
print (A.dot(evecs[:,0]))
print (evals[0]*evecs[:,0])

print (A.dot(evecs[:,0]))
print (la.eigvalsh(A)[2]*evecs[:,0])


[-1.75902942  3.40592034 13.35310908]
[13.35310908+0.j -1.75902942+0.j  3.40592034+0.j]
 ------------- 
[ 5.69695953  5.842149   10.5697431 ]
[ 5.69695953+0.j  5.842149  +0.j 10.5697431 +0.j]
[ 5.69695953  5.842149   10.5697431 ]
[ 5.69695953  5.842149   10.5697431 ]


In [15]:
# The eigenvectors are orthonormal
print (np.dot(evecs[:,0], evecs[:,0]))
print (np.dot(evecs[:,0], evecs[:,1]))

1.0000000000000002
-1.6653345369377348e-16


In [16]:
# eigenvector 1 is 
print (evecs[:,0])
# eigenvector 2 is
print (evecs[:,1])


[0.42663918 0.43751227 0.79155671]
[ 0.90353276 -0.24498225 -0.35158534]


In [17]:
# do not have to Transform to use np.dot(,)
print (np.dot(evecs[:,0], evecs[:,1]))
print (np.dot(evecs[:,0].T, evecs[:,1]))

-1.6653345369377348e-16
-1.6653345369377348e-16
