# Single Value Decomposition SVD

In [1]:
from numpy import *

# generating a random system Ax=b
A = floor(random.rand(4,4)*20-10) # generating A
b = floor(random.rand(4,1)*20-10) # generating b

U,s,V = linalg.svd(A) # SVD decomposition of A

# computing the inverse using pinv
pinv     = linalg.pinv(A)
# computing the inverse using the SVD decomposition
pinv_svd = dot(dot(V.T,linalg.inv(diag(s))),U.T)

# this is wrong!! Remember the right formula when u want to inverse a matrix 
pinv_svd2 = dot(dot(V,linalg.inv(diag(s))),U.T)

print ("Inverse computed by lingal.pinv()\n",pinv)
print ("Inverse computed using SVD\n",pinv_svd)
print ("They are just fine")

print ("But remember the correct order, otherwise you will be mistaken, like shown below ")
print ("Inverse computed using WRONG SVD\n",pinv_svd2)

Inverse computed by lingal.pinv()
 [[ 0.01777656  0.08778887  0.02434022 -0.00341857]
 [-0.03972378  0.04997949 -0.0313141   0.02686996]
 [-0.01668262 -0.09777109  0.06946534  0.08013127]
 [-0.06632025 -0.0198277   0.06303842 -0.02570764]]
Inverse computed using SVD
 [[ 0.01777656  0.08778887  0.02434022 -0.00341857]
 [-0.03972378  0.04997949 -0.0313141   0.02686996]
 [-0.01668262 -0.09777109  0.06946534  0.08013127]
 [-0.06632025 -0.0198277   0.06303842 -0.02570764]]
They are just fine
But remember the correct order, otherwise you will be mistaken, like shown below 
Inverse computed using WRONG SVD
 [[ 0.02771983  0.04676482  0.03006423  0.03407497]
 [-0.00446829 -0.05312341 -0.01850258  0.07344101]
 [-0.00508804 -0.12298525  0.07802458  0.03169207]
 [-0.07587113 -0.00476899  0.05512039  0.01601603]]


In [2]:
import numpy as np
A2 = np.matrix([[1,3],
                [0,-1]])
print (A2)

[[ 1  3]
 [ 0 -1]]


In [3]:
U,s,V = linalg.svd(A2)
print (dot(dot(U,diag(s)),V))
print ("    ")
print ("The Singular Values of A2 are: ", s)

[[ 1.00000000e+00  3.00000000e+00]
 [-5.55111512e-17 -1.00000000e+00]]
    
The Singular Values of A2 are:  [3.30277564 0.30277564]


In [4]:
# computing the inverse using pinv
print (linalg.pinv(A2))
# computing the inverse using the SVD decomposition
print (dot(dot(V.T,linalg.inv(diag(s))),U.T))

SyntaxError: invalid syntax (<ipython-input-4-bea62fa9ae09>, line 2)

In [ ]:
from numpy import linalg as LA
S =(dot(A2.T,A2))
w, v = LA.eig(S)

print ("    ")
print ("The sqrt of the EigenValues of T(A2)*A2 are the same as the Singular Values of A2  ")
print (np.sqrt(w))

In [ ]:
import numpy as np
A3 = np.matrix([[7,-3.0,2.5],
                [0, 1.0, 0 ],
                [0.2, 0,0.3]])
print (A3)
print (" ----------------------- ")
U,s,V = linalg.svd(A3)
print (np.around(dot(dot(U,diag(s)),V),5))
print ("    ")
print ("The Singular Values of A2 are: ", s)
print (" ----------------------- ")
S = (dot(A3.T,A3))
w, v = LA.eig(S)
print ("    ")
print ("The sqrt of the EigenValues of T(A2)*A2 are the same as the Singular Values of A2  ")
print (np.sqrt(w))

In [ ]:
U,s,V = linalg.svd(A3) # SVD decomposition of A
# computing the inverse using pinv
pinv     = linalg.pinv(A3)
# computing the inverse using the SVD decomposition
pinv_svd = dot(dot(V.T,linalg.inv(diag(s))),U.T)

print ("Inverse computed by lingal.pinv()\n",pinv)
print ("Inverse computed using SVD\n",pinv_svd)

print (np.allclose(pinv, pinv_svd))

In [ ]:
print ("and compare A*inv(A)\n",np.around(dot(A3,pinv),5))
print ("and compare A*inv(A)\n",np.around(dot(A3,pinv_svd),5))

In [ ]:
# generating a random system Ax=b

A = floor(random.rand(400,400)*20-10) # generating A
b = floor(random.rand(400,1)*20-10)   # generating b

def inv_svd(A):
    U,s,V = linalg.svd(A) # SVD decomposition of A
    return dot(dot(V.T,linalg.inv(diag(s))),U.T)

def inv_inv(A):
    return linalg.pinv(A)

import timeit
% timeit inv_svd(A)
% timeit inv_inv(A)

# so calculating the inverse of A with linalg.pinv(A) is faster than using SVD

In [ ]:
# This is for A (a 3x2 matrix )
import numpy as np
A4 = np.random.randn(3, 2)

print (A4)
print (" ----------------------- ")
U,s,V = linalg.svd(A4, full_matrices=True)
print (s)
print (V)
print (U.shape)
print (V.shape)
print (s.shape)
SingVa = np.zeros((3, 2))
SingVa[:2, :2] = np.diag(s)

print (SingVa)
print (np.around(dot(dot(U,SingVa),V),5))
print ("    ")
print ("The Singular Values of A2 are: ")
print (s)
print (" ----------------------- ")
S = (dot(A4.T,A4))
w, v = LA.eig(S)
print ("    ")
print ("The sqrt of the EigenValues of T(A2)*A2 are the same as the Singular Values of A2  ")
print (np.sqrt(w))

print (np.allclose(A4, np.dot(U, np.dot(SingVa, V))))

In [ ]:
new_a = np.dot(U, np.dot(SingVa, V))
print (new_a)